---
# tasks file for apparmor

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: apparmor

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: apparmor

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: apparmor
