---
# tasks file for apparmor (Ubuntu specific)

- name: Install Apparmor packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: apparmor_packages
  tags: apparmor

- name: Ensure Apparmor service is started and enabled on boot
  service: name={{ apparmor_service_name }} state=started enabled=yes
  tags: apparmor
